title: iMono  
description: >- 
  Individual research log focusing on Image Processing and Algorithmic Efficiency.
url: "https://monowarhusain.github.io"
baseurl: "/iMono-blog"
theme: minima

timezone: "Asia/Dhaka"
future: true
